version: "3.8"


services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest # prom/cadvisor:latest
    # ports:
    #   - target: 8080
    #     published: 8090
    #     mode: host
    # volumes:
    #   - type: bind
    #     source: /var/run/docker.sock
    #     target: /var/run/docker.sock
    #   - type: bind
    #     source: /
    #     target: /rootfs
    #     read_only: true
    #   - type: bind
    #     source: /var/lib/docker
    #     target: /var/lib/docker
    #     read_only: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      # traefik-public:
      monitor-net:
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: 200M

networks:
  monitoring-network:
    external: true