version: "3.8"

services:
  grafana:
    image: grafana/grafana
    # ports:
    #   - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring-network
    secrets:
      - gf_security_admin_password
    environment:
      GF_SECURITY_ADMIN_PASSWORD: /run/secrets/gf_security_admin_password
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana_router.rule=Host(`grafana.kronk.uz`)"
        - "traefik.http.routers.grafana_router.entrypoints=http,https"
        - "traefik.http.routers.grafana_router.tls.certresolver=leresolver"
        - "traefik.http.routers.grafana_router.service=grafana_service"
        - "traefik.http.services.grafana_service.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.grafana_middleware.redirectscheme.scheme=https"
        # - "traefik.http.routers.grafana_router.middlewares=grafana_middleware"
        - "traefik.http.middlewares.grafana_middleware.redirectscheme.permanent=true"
        # - "traefik.http.routers.grafana_router.tls=true"
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: 0.5
          memory: 512M

volumes:
  grafana_storage:

networks:
  monitoring-network:
    external: true
    driver: overlay

secrets:
  gf_security_admin_password:
    external: true