version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "-config.file=/etc/prometheus/prometheus.yml"
    # ports:
    #   - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-network
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus_router.rule=Host(`prometheus.kronk.uz`)"
        - "traefik.http.routers.prometheus_router.entrypoints=http,https"
        - "traefik.http.routers.prometheus_router.tls.certresolver=leresolver"
        - "traefik.http.routers.prometheus_router.service=prometheus_service"
        - "traefik.http.services.prometheus_service.loadbalancer.server.port=9090"
        - "traefik.http.middlewares.prometheus_middleware.redirectscheme.scheme=https"
        #        - "traefik.http.routers.prometheus_router.middlewares=prometheus_middleware"
        - "traefik.http.middlewares.prometheus_middleware.redirectscheme.permanent=true"
        -  # - "traefik.http.routers.prometheus_router.tls=true"
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: 1.0
          memory: 2G

networks:
  monitoring-network:
    external: true
    driver: overlay
