# docker stack deploy -c cadvisor.yml monitoring

services:
  cadvisor:
    image: prom/cadvisor:latest
    ports:
      - target: 8080
        published: 8090
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true
    networks:
      traefik-public:
    deploy:
      mode: global


networks:
  traefik-public:
    external: true
