global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "node-exporter"
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ["<your-node-ip>:9100"]

  - job_name: "fastapi"
    scrape_interval: 15s
    static_configs:
      - targets: ["fastapi:8000"]

  - job_name: "dockerswarm"
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [__meta_dockerswarm_task_desired_state]
        regex: running
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        regex: .+
        action: keep
      - source_labels: [__meta_dockerswarm_service_label_prometheus_job]
        target_label: job
      - source_labels: [__address__, __meta_dockerswarm_task_port]
        regex: (.+);(.+)
        replacement: ${1}:${2}
        target_label: __address__

  - job_name: "docker-swarm"
    dns_sd_configs:
      - names:
          - "tasks.backend_service"
        type: "A"
        port: 8000

  - job_name: "cadvisor"
    dns_sd_configs:
      - names:
          - "tasks.cadvisor"
        type: "A"
        port: 8080

  - job_name: "node-exporter"
    dns_sd_configs:
      - names:
          - "tasks.node-exporter"
        type: "A"
        port: 9100
